"""Week 6 studio — GIVEN harness. You do NOT edit this file.

It does three jobs so the studio is laptop-only (no Docker, no Ollama):

  1. Brings up the vuln-web app IN-PROCESS on 127.0.0.1 (stdlib http.server), and
     gives you ``get`` / ``post`` helpers plus ``BASE`` — the same wiring as the
     notebook's Docker-optional cell, minus Docker.
  2. Provides the CLASSICAL scanner arm for the duel (a small line-oriented regex
     rule set standing in for Semgrep/CodeQL) — GIVEN, so the duel is runnable.
  3. Loads the SOURCE under test and the HAND-BUILT ground-truth set. The ground
     truth is REUSED from the already-built Duel-2 fixture
     (``projects/duel-2-web/ground_truth.json``) — we do NOT invent a second one.

Everything a scanner reads (``SOURCE``) is the exact file you attack dynamically,
so you can check every tool's finding by eye.
"""

from __future__ import annotations

import json
import re
import sys
import threading
import time
import urllib.parse
import urllib.request
from http.server import ThreadingHTTPServer
from pathlib import Path

from seclab.scan import ScanResult

# --- locate the course root (the dir that contains ``seclab/``) --------------
ROOT = Path(__file__).resolve()
while ROOT != ROOT.parent and not (ROOT / "seclab").is_dir():
    ROOT = ROOT.parent
APP_DIR = ROOT / "labs" / "vuln-web" / "app"
GROUND_TRUTH_FILE = ROOT / "projects" / "duel-2-web" / "ground_truth.json"
sys.path.insert(0, str(APP_DIR))

import vulnweb_app as vulnweb  # noqa: E402  (the target under test)

# The exact source a scanner/LLM reads in Task 2 — the same file you attack.
SOURCE = (APP_DIR / "vulnweb_app.py").read_text()

# --- bring the target up in-process, once ------------------------------------
PORT = 8062
BASE = f"http://127.0.0.1:{PORT}"
_started = False
_lock = threading.Lock()


def serve() -> str:
    """Start the vuln-web app in-process (idempotent). Returns ``BASE``.

    No Docker: this is the ``targets`` fallback the notebook uses when Docker is
    absent. A fresh in-memory DB is created so the SQLi canary row is deterministic.
    """
    global _started
    with _lock:
        if not _started:
            vulnweb.DB = vulnweb.make_db()
            srv = ThreadingHTTPServer(("127.0.0.1", PORT), vulnweb.Handler)
            threading.Thread(target=srv.serve_forever, daemon=True).start()
            time.sleep(0.2)
            _started = True
    return BASE


def get(path: str) -> str:
    serve()
    with urllib.request.urlopen(BASE + path, timeout=10) as r:
        return r.read().decode()


def post(path: str, obj: dict) -> str:
    serve()
    req = urllib.request.Request(
        BASE + path, data=json.dumps(obj).encode(),
        headers={"Content-Type": "application/json"})
    with urllib.request.urlopen(req, timeout=10) as r:
        return r.read().decode()


# Convenience senders for the three sinks (payload -> response string).
def login_send(user_payload: str) -> str:
    return post("/login", {"user": user_payload, "pw": "x"})


def reflect_send(name_payload: str) -> str:
    return get("/?name=" + urllib.parse.quote(name_payload))


def reflect_safe_send(name_payload: str) -> str:
    return get("/safe?name=" + urllib.parse.quote(name_payload))


def ping_send(host_payload: str) -> str:
    return post("/ping", {"host": host_payload})


# --- Task 2, GIVEN: the classical scanner arm --------------------------------
def regex_scanner(source: str) -> list[ScanResult]:
    """A small line-oriented rule set standing in for Semgrep/CodeQL.

    Each rule looks for a vulnerable-looking pattern on a SINGLE line (``re.search``,
    default flags, so ``.`` does not cross newlines). This is how many simple, real
    rules work — and it is why this scanner MISSES the SQLi: in ``vulnweb_app.py``
    the query is split across two lines, so the interpolation is not on the same
    line as ``SELECT``. That miss is a genuine failure mode, not a contrivance, and
    it is the point of the guarantee test in ``test_studio.py``.
    """
    rules = [
        ("do_login", "sqli", r'f"SELECT.*\{.*\}'),      # misses: query spans 2 lines
        ("do_reflect", "xss", r"Hello, \{name\}"),
        ("do_ping", "cmdi", r'f"ping -c 1 \{host\}'),
    ]
    out = []
    for loc, rule, pat in rules:
        if re.search(pat, source):
            out.append(ScanResult(rule=rule, location=loc,
                                  tool="regex-scanner", confidence="medium"))
    return out


# --- Task 2, GIVEN: a canned LLM review (so the studio needs no Ollama) -------
# This is what a small local model actually returns when asked "find the vulns in
# this file": it catches the three obvious sinks (high recall), then adds a
# confident HALLUCINATION (Broken Access Control, in an app with no auth code) and
# a WRONG-LOCATION finding (flags the SAFE endpoint). In the studio you replace
# this string with real output from ``seclab.LLM``; the parsing you write in
# ``starter.parse_llm_review`` stays the same.
RAW_LLM_REVIEW = """\
I reviewed vulnweb_app.py and found the following vulnerabilities:

1. [HIGH] SQL Injection in do_login: the query is built with f-string
   interpolation of `user` and `pw`, so an attacker can bypass authentication.
2. [HIGH] Reflected XSS in do_reflect: the `name` parameter is placed into the
   HTML response without any output encoding.
3. [HIGH] Command Injection in do_ping: the `host` value is concatenated into a
   shell command string.
4. [HIGH] Broken Access Control in do_login: there is no session or role check
   guarding the admin record, so any user can reach privileged data.
5. [MEDIUM] Reflected XSS in do_reflect_safe: the `name` parameter is reflected
   back to the user in the response.
"""

# GIVEN alias map: prose vulnerability names -> the canonical rule string used by
# ScanResult.key() and by the ground-truth set. Your parser (Task 2) uses this.
RULE_ALIASES = {
    "sql injection": "sqli",
    "reflected xss": "xss",
    "xss": "xss",
    "command injection": "cmdi",
    "broken access control": "broken-access-control",
}


def load_ground_truth() -> set[tuple]:
    """Load the HAND-VERIFIED ground truth for vuln-web and return the set of
    ``(rule, location)`` keys, normalized exactly as ``ScanResult.key()`` does.

    REUSE, do not reinvent: this reads the already-built Duel-2 fixture at
    ``projects/duel-2-web/ground_truth.json`` — the same set Duel 2 (week 8) is
    graded against. Building an independent, honest ground truth (by reading the
    source, not by running a tool) is the whole point of the duel.
    """
    data = json.loads(GROUND_TRUTH_FILE.read_text())
    return {(f["rule"].strip().lower(), f["location"].strip().lower())
            for f in data["findings"]}
